### ISSUE TITLE
Building cheat, Mechanics cheats.. etc doesn't work

### ISSUE THREAD

**Issue by vstgm** [Emilprivate/Esd.GHJ#3]
thank you for nice cheat first of all, i found features on skills/ cheat options doesn't work.

and i wonder if you can add 'item add' features for modded items :)

**Comment by Emilprivate** [comment]
There's a small bug with the misc cheats that require you to relog for them to work properly, see if that fixes it. 

1. Activate one of the misc cheats (building, mechanics, whatever)
2. Log out of the server
3. Log back into the server
4. Test them

For modded items I would need a comprehensive list detailing all the base.ids for the items for me to add them in, however, I've provided a manual way of adding items in the items list window that can be utilized to add the items manually if the item ids are known. 

Perhaps in the future, something like a JSON file interpreter could be added for people to manually add lists of items. Anyone reading this could potentially work on something like this, I have already implemented functions to get/load files in the [configs header file](https://github.com/Emilprivate/Esd.GHJ/blob/main/Project%20Zomboid/Prototypes/Prototype5/configsystem.h) that can be modified/utilized.
