### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kyupiak** [Emilprivate/Esd.GHJ#4]
what can server admins see when you go into god mode/give yourself an item? (in logs I assume) I was banned from a server after about 1 minute after activating the mechanics cheat and repairing a vehicle, are you able to give me more insight on what I should/shouldn't do to get detected? I'm curious what the admins can see me doing in the logs regarding any cheating.

**Comment by FigmaFan** [comment]
I'm not too sure about what they can & can't see in logs (they definetely see when you level up a skill) but make sure to not use any feature that utilizes one of the games "cheat" methods (look in the source code what the specific features are doing!), for example: "setUnlimitedCarry(boolean value)", they will just change the value of some bool which can easily be checked by anti-cheat plugins.
